### ISSUE TITLE
Background index.html di branch "responsive" masih belum bisa

### ISSUE THREAD

**Issue by Ordinal43** [joshuagibeonm/ProgWeb-Ceria#2]
@joshuagibeonm coba cek **./css/welcome.css** dari kmren aku nyoba gambar backgroundnya gamau. padahal aku kasih warna ttp muncul bgnya

**Comment by joshuagibeonm** [comment]
Fixed~

**Comment by Ordinal43** [comment]
fixed. thanks for the info
