### ISSUE TITLE
Responsive problem in home.html in responsive branch

### ISSUE THREAD

**Issue by joshuagibeonm** [joshuagibeonm/ProgWeb-Ceria#3]
If we use a device with screen width less than 400, the navigation bar tab is too small and the text is not centered.

@Ordinal43 Maybe you could use different approach to create responsive design for home.html, for example when device screen width is less than 400, hide the navigation bar and use side menu bar.

Check CSS media query, maybe it will help you to fix this issue.

**Comment by Ordinal43** [comment]
Will try to fix. Thanks for the advice
